-- CreateEnum
CREATE TYPE "Role" AS ENUM ('EMPLOYEE', 'MANAGER', 'HR_ADMIN', 'ORG_ADMIN');

-- CreateEnum
CREATE TYPE "Uom" AS ENUM ('NUMERIC', 'PERCENT', 'TIMELINE', 'ZERO_BASED');

-- CreateEnum
CREATE TYPE "GoalDirection" AS ENUM ('HIGHER_IS_BETTER', 'LOWER_IS_BETTER');

-- CreateEnum
CREATE TYPE "GoalStatus" AS ENUM ('NOT_STARTED', 'ON_TRACK', 'COMPLETED');

-- CreateEnum
CREATE TYPE "ThrustArea" AS ENUM ('BUSINESS_GROWTH', 'OPERATIONAL_EXCELLENCE', 'TECHNOLOGY_AND_INNOVATION', 'COMPLIANCE_AND_RISK');
